apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8090
      protocol: TCP
    - name: agent
      port: 50000
      targetPort: 50000
      protocol: TCP
  selector:
    app: jenkins
