apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-agent-deployment
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-agent
  template:
    metadata:
      labels:
        app: jenkins-agent
    spec:
      securityContext:
        fsGroup: 1000

      containers:
      - name: jnlp
        image: jenkins/inbound-agent:latest
        env:
        - name: JENKINS_URL
          value: http://jenkins-service.jenkins.svc.cluster.local:80
        - name: JENKINS_AGENT_NAME
          value: minikube-agent-1
        - name: JENKINS_SECRET
          valueFrom:
            secretKeyRef:
              name: jenkins-agent-secret
              key: jenkins-agent-secret
        volumeMounts:
        - name: agent-workspace
          mountPath: /var/jenkins_home

      volumes:
      - name: agent-workspace
        emptyDir: {}
