apiVersion: v1
kind: Secret
metadata:
  name: jenkins-agent-secret
  namespace: jenkins
type: Opaque
stringData:
  jenkins-agent-secret: "f6fa50bff6ad844c7d4b183421e1d8b34e622346257a824b7cb83217eff9995e"
