apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix-relay
  namespace: mail-relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix-relay
  template:
    metadata:
      labels:
        app: postfix-relay
    spec:
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
      containers:
        - name: postfix-relay
          # Simple Postfix server for outgoing mail relay
          image: mwader/postfix-relay:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 25
          env:
            - name: maildomain
              value: example.com
            - name: smtp_user
              valueFrom:
                secretKeyRef:
                  name: postfix-relay-secret
                  key: smtp_user
          readinessProbe:
            tcpSocket:
              port: 25
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 25
            initialDelaySeconds: 30
            periodSeconds: 10
