# ollama-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: automation
  name: ollama-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
