apiVersion: v1
kind: Service
metadata:
  name: wireguard
spec:
  type: NodePort
  ports:
    - port: 51820
      protocol: UDP
      targetPort: 51820
      nodePort: 30518
  selector:
    app: wireguard
